-- Migration v26 — entity_edges table
-- Applied: 2026-05-24 (Phase 1 of relationship-completeness sprint)
-- Purpose: Universal predicate-based edge table for entity-entity relationships.
--          Distinct from ownership_edges (which is company-ownership-centric).
--          First use: COMPETES_WITH for drug-drug competitive relationships.
--          Future predicates: SIMILAR_TO, DERIVED_FROM, BLOCKS_PATHWAY, etc.
--
-- Design principles:
--   • subject and object types are open (drug, company, target, area)
--   • predicate is an allowlisted enum; extend as needed
--   • COMPETES_WITH is undirected in business logic but stored as bidirectional rows
--     so "WHERE subject_id = X AND predicate = 'COMPETES_WITH'" returns all competitors
--   • edges can carry area_id scope — two drugs may compete in one area but not another
--   • confidence mirrors the platform standard: confirmed / supported / inferred
--
-- Generation method column:
--   'deterministic'   — generated by rule (no LLM) — highest trust
--   'llm_assisted'    — LLM contributed to the classification
--   'manual'          — entered by human reviewer

CREATE TABLE IF NOT EXISTS entity_edges (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Subject
    subject_type        TEXT NOT NULL CHECK (subject_type IN ('drug', 'company', 'target', 'area')),
    subject_id          TEXT NOT NULL,

    -- Predicate
    predicate           TEXT NOT NULL CHECK (predicate IN (
                            'COMPETES_WITH',
                            'SIMILAR_TO',
                            'DERIVED_FROM',
                            'TARGETS',
                            'ACTIVE_IN'
                        )),

    -- Object
    object_type         TEXT NOT NULL CHECK (object_type IN ('drug', 'company', 'target', 'area')),
    object_id           TEXT NOT NULL,

    -- Scope (optional — a COMPETES_WITH edge is scoped to an area)
    scope_area_id       TEXT,

    -- Provenance
    confidence_level    TEXT NOT NULL DEFAULT 'inferred'
                        CHECK (confidence_level IN ('confirmed', 'supported', 'inferred')),
    source_url          TEXT,
    generation_method   TEXT NOT NULL DEFAULT 'manual'
                        CHECK (generation_method IN ('deterministic', 'llm_assisted', 'manual')),

    -- Rationale (why was this edge created?)
    rationale           TEXT,

    -- Status
    status              TEXT NOT NULL DEFAULT 'active'
                        CHECK (status IN ('active', 'deprecated', 'disputed')),

    -- Audit
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by          TEXT NOT NULL DEFAULT 'system',
    notes               TEXT,

    -- Uniqueness: one edge per (subject, predicate, object, scope)
    CONSTRAINT uq_entity_edge UNIQUE (subject_type, subject_id, predicate, object_type, object_id, scope_area_id)
);

CREATE INDEX IF NOT EXISTS idx_entity_edges_subject    ON entity_edges(subject_type, subject_id);
CREATE INDEX IF NOT EXISTS idx_entity_edges_object     ON entity_edges(object_type, object_id);
CREATE INDEX IF NOT EXISTS idx_entity_edges_predicate  ON entity_edges(predicate);
CREATE INDEX IF NOT EXISTS idx_entity_edges_area       ON entity_edges(scope_area_id);
CREATE INDEX IF NOT EXISTS idx_entity_edges_status     ON entity_edges(status);

-- Compound index for the most common query: "all competitors of drug X in area Y"
CREATE INDEX IF NOT EXISTS idx_entity_edges_compete_lookup
    ON entity_edges(subject_id, predicate, scope_area_id)
    WHERE predicate = 'COMPETES_WITH';

-- Seed rows: inserted by scripts/seed_competes_with.py immediately after migration.
-- See that script for the full edge list and uncertain-case documentation.
