#!/usr/bin/env python3
"""Seed the data_sources registry — every external API/source Meridian is connected to.
Idempotent upsert. Derived from docs/API_INTEGRATION_LANDSCAPE.md + integration rounds 1-15."""
import json, os, urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
SB = "https://tghntyofptvfhmtchwcv.supabase.co/rest/v1"
KEY = open(os.path.join(ROOT, ".supabase_service_key")).read().strip()

# (key, name, category, what_we_get, tables_fed, access, status, status_note, api_url, sort)
S = [
 ("ctgov","ClinicalTrials.gov v2","clinical",
  "Every registered trial: phase, sponsor, collaborators, sites, dates, enrollment, design, results sections. Drives trials, catalysts, and trial-quality scoring.",
  ["trial_facts","trial_registries","trial_results","catalysts","trial_design_quality"],"free","active",None,
  "https://clinicaltrials.gov/data-api/api",10),
 ("opentargets","Open Targets","science",
  "Target ↔ disease ↔ drug evidence graph: genetic association scores, tractability, mechanisms of action, drug warnings, known-drug links.",
  ["target_intelligence","drug_targets","drug_safety","external_entity_map"],"free","active",None,
  "https://platform.opentargets.org/api",11),
 ("chembl","ChEMBL","science",
  "Molecule-level facts: modality, mechanism class, development phase, identifiers. Arrives via Open Targets drug IDs.",
  ["drug_modalities","external_entity_map"],"free","active",None,"https://www.ebi.ac.uk/chembl/api/data",12),
 ("europepmc","Europe PMC","literature",
  "Open biomedical literature: epidemiology/burden papers for patient intelligence, drug evidence citations.",
  ["drug_sources","indication_patient_intelligence","publications"],"free","active",None,
  "https://europepmc.org/RestfulWebService",13),
 ("pubmed","PubMed E-utilities","literature",
  "Canonical literature index — resolved 100% of the 1,821 PMIDs cited by trials into full publication records.",
  ["publications","drug_sources"],"free","active",None,"https://www.ncbi.nlm.nih.gov/books/NBK25501/",14),
 ("crossref","Crossref","literature",
  "DOI metadata + citation counts (cited_by 1,830 refreshed). DOI normalization and dedupe.",
  ["publications"],"free","active",None,"https://api.crossref.org",15),
 ("openalex","OpenAlex","literature",
  "Conference abstracts (DDW/ECCO/ACR…), author/institution graph — 1,060 authorship rows, 6 KOLs unified across trials + papers. Honest gap: titles only, no abstract bodies.",
  ["conference_abstracts","conference_abstract_signals","publication_authors","kols","institutions"],"free","partial",
  "abstract_text is empty in OpenAlex — readout text needs society supplements or paid",None,16),
 ("semanticscholar","NIH RePORTER","science",
  "NIH grant funding by target/disease — upstream academic signal (TL1A $3.9M, IL-13 $11M) years before trials.",
  ["grants"],"free","active",None,"https://api.reporter.nih.gov",17),
 ("openfda","openFDA (Drugs@FDA, FAERS, establishments)","regulatory",
  "US approvals + dates, post-market adverse-event reports (FAERS burden), manufacturing establishment registry.",
  ["fda_approvals","fda_adverse_events","manufacturing_sites","geographic_approvals"],"free","active",None,
  "https://open.fda.gov/apis",20),
 ("dailymed","DailyMed (NLM)","regulatory",
  "Official structured drug labels (SPL): indications, dosing, boxed warnings — 46 labels linked.",
  ["drug_labels","drug_safety"],"free","active",None,"https://dailymed.nlm.nih.gov/dailymed/app-support-web-services.cfm",21),
 ("ema","EMA (bulk medicine data)","regulatory",
  "EU approvals + dates → US-vs-EU approval lag analysis (median +184 days; bimekizumab EU-first).",
  ["eu_approvals"],"free","active",None,"https://www.ema.europa.eu/en/medicines/download-medicine-data",22),
 ("fda_oopd","FDA Orphan Drug designations (OOPD)","regulatory",
  "Official orphan designations — 148 designations across 42 drugs from the OOPD bulk export.",
  ["regulatory_designations"],"free","active","Bulk export reachable from VM; GitHub-runner IPs blocked by Akamai",
  "https://www.accessdata.fda.gov/scripts/opdlisting/oopd/",23),
 ("purplebook","FDA Purple Book + Orange Book","ip",
  "Biologic 12-year reference-product exclusivity + small-molecule patent/exclusivity listings — the exclusivity-cliff map.",
  ["drug_exclusivity","drug_patents"],"free","active",None,"https://purplebooksearch.fda.gov",24),
 ("sec","SEC EDGAR","financial",
  "10-K/10-Q/8-K full text: financing events typed by security (debt vs dilutive vs PIPE), deal/M&A/leadership events from 8-K bodies, cash runway.",
  ["company_filings","company_events","company_financials","deals"],"free","active",None,"https://www.sec.gov/edgar",30),
 ("gleif","GLEIF LEI","entity",
  "Legal-entity identifiers for company disambiguation (68/154 matched) — caught 3 wrong-company bindings.",
  ["companies"],"free","active",None,"https://www.gleif.org/en/lei-data/gleif-api",31),
 ("openfigi","OpenFIGI","entity",
  "Ticker ↔ company crosswalk for financial joins.",
  ["companies"],"free","active","Migrate to /v3 before Jul 2026 sunset","https://www.openfigi.com/api",32),
 ("stocks","Stock price feed","financial",
  "Daily prices for public competitors — market-cap context for runway and deal capacity.",
  ["stock_price_history"],"free","active",None,None,33),
 ("gpatents","Google Patents","ip",
  "Patent families by assignee/target — 224 company patents (TL1A 30, FcRn 26, TSLP 21, IL-23p19 20) incl. the Prometheus anti-TL1A FTO family for ALX001.",
  ["company_patents","drug_patents"],"free","partial",
  "Throttled; big-pharma assignee sweep resumable. True INPADOC families need a free EPO/Lens token",
  "https://patents.google.com",40),
 ("surechembl","SureChEMBL (EBI)","ip",
  "Keyless patent-family graph — every jurisdiction a patent is filed in (INPADOC-style members). Seeds the patent_families layer so each tracked patent has its global family as references.",
  ["patent_families"],"free","active","Transient nginx 503s — runs with retries; full coverage via hosted runner",
  "https://www.surechembl.org/api/v3/api-docs",45),
 ("pharos","Pharos / IDG","science",
  "Target Development Level (druggability tier), ligand counts per target — feeds whitespace/tractability.",
  ["target_intelligence"],"free","active",None,"https://pharos.ncats.nih.gov",41),
 ("uniprot","UniProt","science",
  "Protein-level target detail: function, isoforms, domains.",
  ["target_intelligence"],"free","active",None,"https://www.uniprot.org/help/api",42),
 ("gtopdb","Guide to Pharmacology (GtoPdb)","science",
  "Expert-curated antibody/ligand pharmacology — 26/41 targets enriched (stronger than ChEMBL for biologics).",
  ["target_intelligence"],"free","active",None,"https://www.guidetopharmacology.org/webServices.jsp",43),
 ("reactome","Reactome","science",
  "Curated pathway maps (TL1A→NF-κB, IL-23→Th17) — 190 target-pathway links, pathway-adjacency whitespace signal.",
  ["target_pathways"],"free","active",None,"https://reactome.org/ContentService",44),
 ("rss","News RSS (Fierce, Endpoints, STAT, BioPharma Dive)","news",
  "Real-time industry headlines → homepage news, sentiment scoring per company.",
  ["news_articles","news_sentiment","company_news_sentiment"],"free","active",None,None,50),
 ("gdelt","GDELT","china",
  "Global news incl. Chinese-language — early company/asset mention signal. Noisy; entity-filtered.",
  ["china_intel"],"free","partial","VM egress rate-limited (429s); 3 rows so far",None,51),
 ("ictrp","WHO ICTRP / ChiCTR","china",
  "China-registered trials. ATTEMPTED: WHO dropped the static bulk file and the legacy search endpoint is server-broken; the 14 Ailux-relevant China assets register on CDE/NMPA which is NOT an ICTRP registry.",
  ["china_trials"],"free","attempted_blocked",
  "Real path = CDE/NMPA (chinadrugtrials.org.cn) headless scraper or paid registry (PharmCube/Citeline)",None,52),
 ("cde","CDE/NMPA (chinadrugtrials.org.cn)","china",
  "China's actual trial registry for domestic assets — where the 14 invisible TL1A/IL-23 China assets live.",
  ["china_trials"],"free","planned","Needs headless-browser scraper keyed on Chinese sponsor names — Kyle decision pending",None,53),
]

rows=[dict(source_key=k,display_name=n,category=c,what_we_get=w,tables_fed=t,access=a,status=st,
           status_note=note,api_url=u,sort_order=so) for (k,n,c,w,t,a,st,note,u,so) in S]
r=urllib.request.Request(f"{SB}/data_sources?on_conflict=source_key",method="POST",data=json.dumps(rows).encode())
r.add_header("apikey",KEY);r.add_header("Authorization",f"Bearer {KEY}")
r.add_header("Content-Type","application/json");r.add_header("Prefer","resolution=merge-duplicates,return=minimal")
urllib.request.urlopen(r)
print(f"data_sources: {len(rows)} upserted")
